from map import arkMap

#the island
islandRegions = ["DinoSpawnEntriesArcha", "DinoSpawnEntriesBeach", "DinoSpawnEntriesBee", "DinoSpawnEntriesCave1", "DinoSpawnEntriesCave2-LowSpiderScorp", "DinoSpawnEntriesCave5", "DinoSpawnEntriesCave7-Fliers", "DinoSpawnEntriesCaveIceWater", "DinoSpawnEntriesCaveLava", "DinoSpawnEntriesCaveMegalo", "DinoSpawnEntriesCaveTek_Easy_11", "DinoSpawnEntriesCaveTek_Easy_12", "DinoSpawnEntriesCaveTek_Easy_13", "DinoSpawnEntriesCaveTek_Easy_14", "DinoSpawnEntriesCaveTek_Easy_15", "DinoSpawnEntriesCaveTek_Easy_16", "DinoSpawnEntriesCaveTek_Hard_11", "DinoSpawnEntriesCaveTek_Hard_12", "DinoSpawnEntriesCaveTek_Hard_13", "DinoSpawnEntriesCaveTek_Hard_14", "DinoSpawnEntriesCaveTek_Hard_15", "DinoSpawnEntriesCaveTek_Hard_16", "DinoSpawnEntriesCaveTek_Medium_11", "DinoSpawnEntriesCaveTek_Medium_12", "DinoSpawnEntriesCaveTek_Medium_13", "DinoSpawnEntriesCaveTek_Medium_14", "DinoSpawnEntriesCaveTek_Medium_15", "DinoSpawnEntriesCaveTek_Medium_16", "DinoSpawnEntriesCaveWater", "DinoSpawnEntriesDamiensAtoll", "DinoSpawnEntriesGigant", "DinoSpawnEntriesGigantTekCave", "DinoSpawnEntriesGrassland", "DinoSpawnEntriesIceCave", "DinoSpawnEntriesJungle", "DinoSpawnEntriesMegalania", "DinoSpawnEntriesMonsterIsland", "DinoSpawnEntriesMountain", "DinoSpawnEntriesPelican", "DinoSpawnEntriesPenguins", "DinoSpawnEntriesQuetz", "DinoSpawnEntriesRedwoods", "DinoSpawnEntriesSnow", "DinoSpawnEntriesSwamp", "DinoSpawnEntriesSwampCave", "DinoSpawnEntriesSwampCaveWater", "DinoSpawnEntriesThy", "DinoSpawnEntriesTinyCave", "DinoSpawnEntriesTitano", "DinoSpawnEntriesUnderwaterGround", "DinoSpawnEntriesUnicorn", "DinoSpawnEntries_Beavers", "DinoSpawnEntries_DarkWater", "DinoSpawnEntries_DarkWaterAngler", "DinoSpawnEntries_DarkWater_Lio", "DinoSpawnEntries_DarkWater_Mosa", "DinoSpawnEntries_DarkWater_Mosa_Caves", "DinoSpawnEntries_DarkWater_Plesia", "DinoSpawnEntries_DarkWater_Tuso", "DinoSpawnEntries_DeepWater", "DinoSpawnEntries_InlandWater", "DinoSpawnEntries_Ocean", "DinoSpawnEntries_OceanCaveHard", "DinoSpawnEntries_OceanCaveMedium", "DinoSpawnEntries_RedwoodWater", "DinoSpawnEntries_ShallowWater", "DinoSpawnEntries_SwampWater"]
theIsland = arkMap("The Island", islandRegions)

#the center
centerRegions = ["CustomAnglerSpawner","CustomPenguinSpawner","GrasslandsUnderArea_WaterSpawn","IceCaveWater_Spawner","IceCave_Spawner","LavaBeach_Spawn","LavaWater_Spawn","Lava_Spawn","Lava_Upper_Spawn","MiniCaveBearSpawner","SnowGrasslandsUnderArea_Spawn","SnowGrasslands_Spawn","SnowyMountain_Spawn","UnderwaterCaveSpawn","DinoSpawnEntriesArcha","DinoSpawnEntriesBeach","DinoSpawnEntriesBee","DinoSpawnEntriesCave1","DinoSpawnEntriesCave5","DinoSpawnEntriesCave5_Tough","DinoSpawnEntriesCaveMegalo","DinoSpawnEntriesGigant","DinoSpawnEntriesGrassland","DinoSpawnEntriesJungle","DinoSpawnEntriesMegalania","DinoSpawnEntriesMonsterIsland","DinoSpawnEntriesMountain","DinoSpawnEntriesPelican","DinoSpawnEntriesQuetz","DinoSpawnEntriesRedwoods","DinoSpawnEntriesSnow","DinoSpawnEntriesSwamp","DinoSpawnEntriesThy","DinoSpawnEntriesTitano","DinoSpawnEntries_Beavers","DinoSpawnEntries_DarkWater","DinoSpawnEntries_DarkWater_Lio","DinoSpawnEntries_DarkWater_Mosa","DinoSpawnEntries_DarkWater_Tuso","DinoSpawnEntries_DeepWater","DinoSpawnEntries_GenericWater","DinoSpawnEntries_InlandWater","DinoSpawnEntries_Ocean","DinoSpawnEntries_OceanUnderworld","DinoSpawnEntries_ShallowWater","DinoSpawnEntries_SwampWater"]
theCenter = arkMap("The Center", centerRegions)

#scorched earth
scorchedRegions = ["DinoSpawnEntriesBee","DinoSpawnEntriesCaveMegalo","DinoSpawnEntriesMegalania","DinoSpawnEntriesPhoenix","SE_DinoSpawnEntriesBadlands","SE_DinoSpawnEntriesCanyonCave","SE_DinoSpawnEntriesCanyons","SE_DinoSpawnEntriesDunes","SE_DinoSpawnEntriesEZMode","SE_DinoSpawnEntriesGreenDesert","SE_DinoSpawnEntriesMountain","SE_DinoSpawnEntriesMountainCave","SE_DinoSpawnEntriesOasis","SE_DinoSpawnEntriesRuinsCave","SE_DinoSpawnEntriesRuinsCaveNoGolem","SE_DinoSpawnEntriesSandworm","SE_DinoSpawnEntriesWater","SE_DinoSpawnEntriesWyvern","SE_DinoSpawnEntriesWyvernTrench","SE_DinoSpawnEntries_RexSolo"]
scorchedEarth = arkMap("Scorched Earth", scorchedRegions)

#aberration
aberrationRegions = ["AB_DinoSpawnEntriesRockDrake","AB_DinoSpawnEntries_Basilisks","AB_DinoSpawnEntries_BioLumCave","AB_DinoSpawnEntries_DrakeTrench","AB_DinoSpawnEntries_ElementCave","AB_DinoSpawnEntries_ElementWater","AB_DinoSpawnEntries_ElementalChamber","AB_DinoSpawnEntries_FertileCave","AB_DinoSpawnEntries_OctoBat","AB_DinoSpawnEntries_RockDrake","AB_DinoSpawnEntries_TwitchBioLand","AB_DinoSpawnEntries_TwitchBioWater","AB_DinoSpawnEntries_TwitchFertileLand","AB_DinoSpawnEntries_TwitchFertileLandEasy","AB_DinoSpawnEntries_TwitchFertileWater","AB_DinoSpawnEntries_TwitchFertileWaterCave3","AB_DinoSpawnEntries_TwitchFertileWaterEasy","AB_DinoSpawnEntries_XenoQueens","AB_DinoSpawnEntries_Xenos","SE_DinoSpawnEntries_ChupaCabraSurface","DinoSpawnEntriesBee","DinoSpawnEntriesChupa"]
aberration = arkMap("Aberration", aberrationRegions)

#ragnarok
ragnarokRegions = ["Ragnarok_DinoSpawnEntriesIceWyvern","DinoSpawnEntries_Lobster","DinoSpawnEntries_Ragnarok_Bear","DinoSpawnEntries_Ragnarok_Castle","DinoSpawnEntries_Ragnarok_Center","DinoSpawnEntries_Ragnarok_CenterWater","DinoSpawnEntries_Ragnarok_DeepWater","DinoSpawnEntries_Ragnarok_Golem","DinoSpawnEntries_Ragnarok_Griffin","DinoSpawnEntries_Ragnarok_Iceworm","DinoSpawnEntries_Ragnarok_Jerboa","DinoSpawnEntries_Ragnarok_Jungle","DinoSpawnEntries_Ragnarok_MonkeyIsland","DinoSpawnEntries_Ragnarok_Mudslide","DinoSpawnEntries_Ragnarok_Ocean","DinoSpawnEntries_Ragnarok_PolarBear","DinoSpawnEntries_Ragnarok_Scotland","DinoSpawnEntries_Ragnarok_SnowForest","DinoSpawnEntries_Ragnarok_SnowPlains","DinoSpawnEntriesArcha","DinoSpawnEntriesBeach","DinoSpawnEntriesBee","DinoSpawnEntriesCave1","DinoSpawnEntriesCave2","DinoSpawnEntriesCave5_Tough","DinoSpawnEntriesCaveMegalo","DinoSpawnEntriesDamiensAtoll","DinoSpawnEntriesGigant","DinoSpawnEntriesGrassland","DinoSpawnEntriesMegalania","DinoSpawnEntriesMonsterIsland","DinoSpawnEntriesMountain","DinoSpawnEntriesPelican","DinoSpawnEntriesPenguins","DinoSpawnEntriesQuetz","DinoSpawnEntriesRedwoods","DinoSpawnEntriesSnow","DinoSpawnEntriesSwamp","DinoSpawnEntriesThy","DinoSpawnEntriesTinyCave","DinoSpawnEntriesTitano","DinoSpawnEntriesUnicorn","DinoSpawnEntriesWater","DinoSpawnEntries_Beavers","DinoSpawnEntries_DarkWater","DinoSpawnEntries_DarkWaterAngler","DinoSpawnEntries_DarkWater_Lio","DinoSpawnEntries_DarkWater_Mosa","DinoSpawnEntries_DarkWater_Tuso","DinoSpawnEntries_DeepWater","DinoSpawnEntries_InlandWater","DinoSpawnEntries_RedwoodWater","DinoSpawnEntries_SwampWater","SE_DinoSpawnEntriesBadlands","SE_DinoSpawnEntriesCanyons","SE_DinoSpawnEntriesDunes","SE_DinoSpawnEntriesGreenDesert","SE_DinoSpawnEntriesMountain","SE_DinoSpawnEntriesOasis","SE_DinoSpawnEntriesSandworm","SE_DinoSpawnEntriesWyvern","SE_DinoSpawnEntriesWyvernTrench"]
ragnarok = arkMap("Ragnarok", ragnarokRegions)

mapList = [theIsland, theCenter, scorchedEarth, aberration, ragnarok]